import Head from "next/head";

import HomePage from "./Home/HomePage";

export default function Index() {
  return (
    <div>
      <Head>
        <title>PortraitScopie - Myrhmica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </div>
  );
}
