import Head from "next/head";
import styles from "../styles/Home.module.css";

import HomePage from "./Home/HomePage";

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PortraitScopie - Myrhmica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HomePage />
      </main>
    </div>
  );
}
